"""add error event table

Revision ID: d4a08b7a2f4b
Revises: 17278b0c3e60
Create Date: 2025-06-26 08:23:59.163588

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a08b7a2f4b'
down_revision = '17278b0c3e60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_error_id', sa.Integer(), nullable=False),
    sa.Column('group_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_error_id'], ['raw_errors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_group_timestamp', 'error_events', ['group_fingerprint', 'timestamp'], unique=False)
    op.create_index('idx_raw_error_id', 'error_events', ['raw_error_id'], unique=False)
    op.create_index(op.f('ix_error_events_group_fingerprint'), 'error_events', ['group_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_events_group_fingerprint'), table_name='error_events')
    op.drop_index('idx_raw_error_id', table_name='error_events')
    op.drop_index('idx_group_timestamp', table_name='error_events')
    op.drop_table('error_events')
    # ### end Alembic commands ###
