"""add group model

Revision ID: b0d579c3e099
Revises: ab5d0b9b64c7
Create Date: 2025-06-11 16:42:37.509725

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d579c3e099'
down_revision = 'ab5d0b9b64c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('example_message', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('occurrences', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_groups_fingerprint'), 'error_groups', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_error_groups_id'), 'error_groups', ['id'], unique=False)
    op.create_index(op.f('ix_error_groups_service'), 'error_groups', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_groups_service'), table_name='error_groups')
    op.drop_index(op.f('ix_error_groups_id'), table_name='error_groups')
    op.drop_index(op.f('ix_error_groups_fingerprint'), table_name='error_groups')
    op.drop_table('error_groups')
    # ### end Alembic commands ###
